
import type { User as FirebaseUser } from "firebase/auth";
import type { Timestamp, FieldValue } from "firebase/firestore";

export type UserRole = "student" | "teacher";

export interface AppUser extends FirebaseUser {
  role?: UserRole;
  grade?: string;
  division?: string;
  displayName?: string | null;
  photoURL?: string | null; // Make sure photoURL is part of AppUser
}

export interface Notice {
  id: string; // Document ID from Firestore
  title: string;
  content: string;
  postedByUid: string;
  postedByName: string;
  timestamp: Timestamp | FieldValue; // Firestore Timestamp on read, FieldValue on write
  displayDate?: string; // For client-side display after conversion
  grade?: string | null; // Target grade
  division?: string | null; // Target division
}

export interface Homework {
  id: string;
  title: string;
  description?: string;
  fileUrl?: string; // URL to the attached file
  fileName?: string;
  postedByUid: string;
  postedByName: string;
  timestamp: Timestamp | FieldValue;
  displayDate?: string;
  dueDate?: string;
  subject?: string;
  grade: string;
  division: string;
}

export interface HomeworkSubmission {
  id?: string; // Auto-generated by Firestore or can be {homeworkId}_{studentId}
  homeworkId: string;
  studentId: string;
  studentName: string; // Denormalized for easier querying/display by teacher
  grade: string;
  division: string;
  homeworkTitle: string; // Denormalized for easier display by teacher
  completedAt: Timestamp | FieldValue;
  status: 'completed'; // Could be extended (e.g., 'submitted', 'late')
}


export interface Circular {
  id: string;
  title: string;
  description?: string;
  fileUrl?: string;
  fileName?: string;
  postedByUid: string;
  postedByName: string;
  timestamp: Timestamp | FieldValue;
  displayDate?: string;
  grade?: string | null;
  division?: string | null;
}

export interface Textbook {
  id: string;
  title: string;
  subject: string;
  fileUrl: string; // URL to PDF
  coverImageUrl?: string;
  fileName?: string;
  postedByUid: string;
  postedByName: string;
  timestamp: Timestamp | FieldValue;
  grade: string;
}

export interface PhotoGalleryAlbum {
  id: string;
  title: string;
  description?: string;
  images: { url: string; alt?: string }[];
  postedByUid: string;
  postedByName: string;
  eventDate?: string;
  timestamp: Timestamp | FieldValue;
}

export interface StudentProfile {
  uid: string;
  firstName: string;
  middleName?: string;
  lastName: string;
  motherName?: string;
  dateOfBirth?: string;
  gender?: string;
  grade: string; 
  division: string; 
  contactNumber?: string;
  aadharCardNumber?: string;
  penNumber?: string;
  grNumber?: string;
  religion?: string;
  caste?: string;
  fullAddress?: string;
  photoUrl?: string;
  email?: string; 
}

export interface LiveClass {
  id: string;
  subject: string; 
  meetingLink: string;
  description?: string;
  postedByUid: string;
  postedByName: string;
  timestamp: Timestamp | FieldValue;
  displayDate?: string;
  grade?: string | null;
  division?: string | null;
}

// Attendance Types
export type AttendanceStatus = "Present" | "Absent" | "Late" | "Excused";

export interface StudentAttendanceRecord {
  [studentUid: string]: AttendanceStatus;
}

export interface DailyAttendanceLog {
  id?: string; // YYYY-MM-DD_GRADE_DIVISION
  date: string; // YYYY-MM-DD
  grade: string;
  division: string;
  studentRecords: StudentAttendanceRecord;
  markedByTeacherId: string;
  markedByTeacherName: string;
  lastUpdatedAt: Timestamp | FieldValue;
}

export type LeaveApplicationStatus = "Pending" | "Approved" | "Rejected";

export interface LeaveApplication {
  id?: string; // Auto-generated by Firestore
  studentUid: string;
  studentName: string;
  grade: string;
  division: string;
  leaveStartDate: string; // YYYY-MM-DD
  leaveEndDate: string;   // YYYY-MM-DD
  reason: string;
  applicationDate: Timestamp | FieldValue;
  status: LeaveApplicationStatus;
  reviewedByTeacherId?: string;
  reviewedByTeacherName?: string;
  reviewTimestamp?: Timestamp | FieldValue;
  teacherComments?: string; // Optional: for teachers to add comments during review
}

